transport {
  type = "TCP"
  #NIO NATIVE
  server = "NIO"
  #开启心跳
  heartbeat = true
  #启用客户端批量发送请求
  enableClientBatchSendRequest = true
  #netty线程工厂
  threadFactory {
    bossThreadPrefix = "NettyBoss"
    workerThreadPrefix = "NettyServerNIOWorker"
    serverExecutorThread-prefix = "NettyServerBizHandler"
    shareBossWorker = false
    clientSelectorThreadPrefix = "NettyClientSelector"
    clientSelectorThreadSize = 1
    clientWorkerThreadPrefix = "NettyClientWorkerThread"
    #netty boss线程大小，UDT不使用
    bossThreadSize = 1
    #自动默认固定或8
    workerThreadSize = 8
  }
  shutdown {
    #销毁服务器时等待秒数
    wait = 3
  }
  serialization = "seata"
  compressor = "none"
}
service {
  #事务服务组映射
  vgroupMapping.offercat_group = "default"
  #仅当registry.type=file时支持
  default.grouplist = "127.0.0.1:8091"
  #降级，当前不支持
  enableDegrade = false
  #禁用seata
  disableGlobalTransaction = false
}

registry {
  # 文件注册
  type = "file"

  nacos {
    application = "seata-server"
    serverAddr = "127.0.0.1:8848"
    group = "SEATA_GROUP"
    namespace = ""
    cluster = "default"
    username = ""
    password = ""
  }

  eureka {
    serviceUrl = "http://localhost:8761/eureka"
    application = "default"
    weight = "1"
  }

  redis {
    serverAddr = "localhost:6379"
    db = 0
    password = ""
    cluster = "default"
    timeout = 0
  }

  zk {
    cluster = "default"
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
  }

  consul {
    cluster = "default"
    serverAddr = "127.0.0.1:8500"
    aclToken = ""
  }

  etcd3 {
    cluster = "default"
    serverAddr = "http://localhost:2379"
  }

  sofa {
    serverAddr = "127.0.0.1:9603"
    application = "default"
    region = "DEFAULT_ZONE"
    datacenter = "DefaultDataCenter"
    cluster = "default"
    group = "SEATA_GROUP"
    addressWaitTime = "3000"
  }

  file {
    name = "file.conf"
  }
}

config {
  # 文件配置
  type = "file"

  nacos {
    serverAddr = "127.0.0.1:8848"
    namespace = ""
    group = "SEATA_GROUP"
    username = ""
    password = ""
    dataId = "seataServer.properties"
  }

  consul {
    serverAddr = "127.0.0.1:8500"
    aclToken = ""
    keyPrefix = "seata."
  }

  apollo {
    appId = "seata-server"
    apolloMeta = "http://192.168.1.204:8801"
    namespace = "application"
    apolloAccesskeySecret = ""
  }

  zk {
    serverAddr = "127.0.0.1:2181"
    sessionTimeout = 6000
    connectTimeout = 2000
    username = ""
    password = ""
    nodePath = "/seata/config"
  }

  etcd3 {
    serverAddr = "http://localhost:2379"
  }

  springCloudConfig {
    application = "default"
    profile = "default"
    label = "master"
    serverAddr = "http://localhost:8888"
  }

  file {
    name = "file.conf"
  }
}
